using System.Collections.Generic;

public class EnemyConstants
{
    public static readonly Dictionary<EnemyType, string> DisplayName = new Dictionary<EnemyType, string>() {
        { EnemyType.Sheep, "Sheep" },
        { EnemyType.Wolf, "Wolf" },
        { EnemyType.Skeleton, "Skeleton" },
        { EnemyType.Acolyte, "Acolyte" },
        { EnemyType.Spider, "Spider" },
        { EnemyType.Swordsman, "Swordsman" },
        { EnemyType.Grunt, "Grunt" },
        { EnemyType.Temptress, "Temptress" },
        { EnemyType.Shade, "Shade" },
        { EnemyType.MudGolem, "Mud Golem" },
        { EnemyType.Treant, "Treant" },
        { EnemyType.RotGolem, "Rot Golem" },
        { EnemyType.Knight, "Knight" },
        { EnemyType.VengefulSpirit, "Vengeful Spirit" },
        { EnemyType.ForestTroll, "Forest Troll" },
        { EnemyType.Wyvern, "Wyvern" },
        { EnemyType.Voidwalker, "Voidwalker" },
        { EnemyType.FacelessOne, "Faceless One" },
        { EnemyType.Dragonspawn, "Dragonspawn" },
        { EnemyType.SeaTurtle, "Sea Turtle" },
        { EnemyType.Banshee, "Banshee" },
        { EnemyType.SiegeEngine, "Siege Engine" },
        { EnemyType.KoboldGeomancer, "Kobold Geomancer" },
        { EnemyType.Infernal, "Infernal" },
        { EnemyType.DeathRevenant, "Death Revenant" },
        { EnemyType.SatyrShadowdancer, "Satyr Shadowdancer" },
        { EnemyType.CryptFiend, "Crypt Fiend" },
        { EnemyType.SpiritWalker, "Spirit Walker" },
        { EnemyType.Necromancer, "Necromancer" },
        { EnemyType.AncientWendigo, "Ancient Wendigo" },
        { EnemyType.GryphonRider, "Gryphon Rider" },
        { EnemyType.OgreMagi, "Ogre Magi" },
        { EnemyType.Abomination, "Abomination" },
        { EnemyType.ChaosWarden, "Chaos Warden" },
        { EnemyType.MountainGiant, "Mountain Giant" },
        { EnemyType.GoblinShredder, "Goblin Shredder" },
        { EnemyType.KodoRider, "Kodo Rider" },
        { EnemyType.FrostWyrm, "Frost Wyrm" },
        { EnemyType.Phoenix, "Phoenix" },
    };
    
    public static readonly Dictionary<EnemyType, int> HP = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 2 },
        { EnemyType.Wolf, 5 },
        { EnemyType.Skeleton, 12 },
        { EnemyType.Acolyte, 24 },
        { EnemyType.Spider, 41 },
        { EnemyType.Swordsman, 64 },
        { EnemyType.Grunt, 75 },
        { EnemyType.Temptress, 100 },
        { EnemyType.Shade, 116 },
        { EnemyType.MudGolem, 188 },
        { EnemyType.Treant, 280 },
        { EnemyType.RotGolem, 1515 },
        { EnemyType.Knight, 580 },
        { EnemyType.VengefulSpirit, 1080 },
        { EnemyType.ForestTroll, 375 },
        { EnemyType.Wyvern, 2187 },
        { EnemyType.Voidwalker, 4140 },
        { EnemyType.FacelessOne, 5455 },
        { EnemyType.Dragonspawn, 7685 },
        { EnemyType.SeaTurtle, 10135 },
        { EnemyType.Banshee, 7980 },
        { EnemyType.SiegeEngine, 19200 },
        { EnemyType.KoboldGeomancer, 36150 },
        { EnemyType.Infernal, 62720 },
        { EnemyType.DeathRevenant, 32368 },
        { EnemyType.SatyrShadowdancer, 54840 },
        { EnemyType.CryptFiend, 74000 },
        { EnemyType.SpiritWalker, 112905 },
        { EnemyType.Necromancer, 130260 },
        { EnemyType.AncientWendigo, 182430 },
        { EnemyType.GryphonRider, 70320 },
        { EnemyType.OgreMagi, 1 }, // TODO
        { EnemyType.Abomination, 227592 },
        { EnemyType.ChaosWarden, 1 }, // TODO
        { EnemyType.MountainGiant, 283055 },
        { EnemyType.GoblinShredder, 405950 },
        { EnemyType.KodoRider, 1 }, // TODO
        { EnemyType.FrostWyrm, 270628 },
        { EnemyType.Phoenix, 603340 },
    };

    public static readonly Dictionary<EnemyType, double> RegenPerSecond = new Dictionary<EnemyType, double>() {
        { EnemyType.Sheep, 0 },
        { EnemyType.Wolf, 0 },
        { EnemyType.Skeleton, 0 },
        { EnemyType.Acolyte, 0 },
        { EnemyType.Spider, 0.5 },
        { EnemyType.Swordsman, 0.5 },
        { EnemyType.Grunt, 3 },
        { EnemyType.Temptress, 1 },
        { EnemyType.Shade, 0 },
        { EnemyType.MudGolem, 1 },
        { EnemyType.Treant, 0 },
        { EnemyType.RotGolem, 3 },
        { EnemyType.Knight, 2 },
        { EnemyType.VengefulSpirit, 2 },
        { EnemyType.ForestTroll, 1.5 },
        { EnemyType.Wyvern, 2 },
        { EnemyType.Voidwalker, 3.5 },
        { EnemyType.FacelessOne, 3.5 },
        { EnemyType.Dragonspawn, 5 },
        { EnemyType.SeaTurtle, 5 },
        { EnemyType.Banshee, 7.5 },
        { EnemyType.SiegeEngine, 0 },
        { EnemyType.KoboldGeomancer, 7.5 },
        { EnemyType.Infernal, 25 },
        { EnemyType.DeathRevenant, 10 },
        { EnemyType.SatyrShadowdancer, 10 },
        { EnemyType.CryptFiend, 15 },
        { EnemyType.SpiritWalker, 15 },
        { EnemyType.Necromancer, 20 },
        { EnemyType.AncientWendigo, 20 },
        { EnemyType.GryphonRider, 25 },
        { EnemyType.OgreMagi, 0 }, // TODO
        { EnemyType.Abomination, 30 },
        { EnemyType.ChaosWarden, 0 }, // TODO
        { EnemyType.MountainGiant, 0 },
        { EnemyType.GoblinShredder, 35 },
        { EnemyType.KodoRider, 0 }, // TODO
        { EnemyType.FrostWyrm, 50 },
        { EnemyType.Phoenix, 100 },
    };

    public static readonly Dictionary<EnemyType, double> MoveSpeed = new Dictionary<EnemyType, double>() {
        { EnemyType.Sheep, 260 },
        { EnemyType.Wolf, 310 },
        { EnemyType.Skeleton, 310 },
        { EnemyType.Acolyte, 335 },
        { EnemyType.Spider, 350 },
        { EnemyType.Swordsman, 310 },
        { EnemyType.Grunt, 350 },
        { EnemyType.Temptress, 350 },
        { EnemyType.Shade, 185 },
        { EnemyType.MudGolem, 335 },
        { EnemyType.Treant, 310 },
        { EnemyType.RotGolem, 335 },
        { EnemyType.Knight, 370 },
        { EnemyType.VengefulSpirit, 360 },
        { EnemyType.ForestTroll, 460 },
        { EnemyType.Wyvern, 200 },
        { EnemyType.Voidwalker, 300 },
        { EnemyType.FacelessOne, 385 },
        { EnemyType.Dragonspawn, 560 },
        { EnemyType.SeaTurtle, 345 },
        { EnemyType.Banshee, 210 },
        { EnemyType.SiegeEngine, 250 },
        { EnemyType.KoboldGeomancer, 410 },
        { EnemyType.Infernal, 510 },
        { EnemyType.DeathRevenant, 415 },
        { EnemyType.SatyrShadowdancer, 425 },
        { EnemyType.CryptFiend, 590 },
        { EnemyType.SpiritWalker, 425 },
        { EnemyType.Necromancer, 425 },
        { EnemyType.AncientWendigo, 360 },
        { EnemyType.GryphonRider, 310 },
        { EnemyType.OgreMagi, 1 }, // TODO
        { EnemyType.Abomination, 620 },
        { EnemyType.ChaosWarden, 100 }, // TODO
        { EnemyType.MountainGiant, 205 },
        { EnemyType.GoblinShredder, 520 },
        { EnemyType.KodoRider, 100 }, // TODO
        { EnemyType.FrostWyrm, 390 },
        { EnemyType.Phoenix, 395 },
    };

    public static readonly Dictionary<EnemyType, int> IncomeReward = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 1 },
        { EnemyType.Wolf, 2 },
        { EnemyType.Skeleton, 3 },
        { EnemyType.Acolyte, 5 },
        { EnemyType.Spider, 6 },
        { EnemyType.Swordsman, 8 },
        { EnemyType.Grunt, 11 },
        { EnemyType.Temptress, 15 },
        { EnemyType.Shade, 22 },
        { EnemyType.MudGolem, 35 },
        { EnemyType.Treant, 30 },
        { EnemyType.RotGolem, 90 },
        { EnemyType.Knight, 95 },
        { EnemyType.VengefulSpirit, 200 },
        { EnemyType.ForestTroll, 340 },
        { EnemyType.Wyvern, 635 },
        { EnemyType.Voidwalker, 825 },
        { EnemyType.FacelessOne, 1000 },
        { EnemyType.Dragonspawn, 1165 },
        { EnemyType.SeaTurtle, 1500 },
        { EnemyType.Banshee, 2100 },
        { EnemyType.SiegeEngine, 1750 },
        { EnemyType.KoboldGeomancer, 4500 },
        { EnemyType.Infernal, 4750 },
        { EnemyType.DeathRevenant, 5000 },
        { EnemyType.SatyrShadowdancer, 6250 },
        { EnemyType.CryptFiend, 7125 },
        { EnemyType.SpiritWalker, 8315 },
        { EnemyType.Necromancer, 9000 },
        { EnemyType.AncientWendigo, 9565 },
        { EnemyType.GryphonRider, 10000 },
        { EnemyType.OgreMagi, 11685 },
        { EnemyType.Abomination, 12000 },
        { EnemyType.ChaosWarden, 13333 },
        { EnemyType.MountainGiant, -25000 },
        { EnemyType.GoblinShredder, -24000 },
        { EnemyType.KodoRider, -30000 },
        { EnemyType.FrostWyrm, -36000 },
        { EnemyType.Phoenix, -125000 },
    };

    public static readonly Dictionary<EnemyType, int> KillReward = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 0 },
        { EnemyType.Wolf, 1 },
        { EnemyType.Skeleton, 3 },
        { EnemyType.Acolyte, 4 },
        { EnemyType.Spider, 5 },
        { EnemyType.Swordsman, 6 },
        { EnemyType.Grunt, 8 },
        { EnemyType.Temptress, 11 },
        { EnemyType.Shade, 16 },
        { EnemyType.MudGolem, 25 },
        { EnemyType.Treant, 50 },
        { EnemyType.RotGolem, 130 },
        { EnemyType.Knight, 50 },
        { EnemyType.VengefulSpirit, 112 },
        { EnemyType.ForestTroll, 200 },
        { EnemyType.Wyvern, 375 },
        { EnemyType.Voidwalker, 487 },
        { EnemyType.FacelessOne, 609 },
        { EnemyType.Dragonspawn, 731 },
        { EnemyType.SeaTurtle, 975 },
        { EnemyType.Banshee, 1425 },
        { EnemyType.SiegeEngine, 2375 },
        { EnemyType.KoboldGeomancer, 3562 },
        { EnemyType.Infernal, 9500 },
        { EnemyType.DeathRevenant, 4250 },
        { EnemyType.SatyrShadowdancer, 5312 },
        { EnemyType.CryptFiend, 6000 },
        { EnemyType.SpiritWalker, 7000 },
        { EnemyType.Necromancer, 7500 },
        { EnemyType.AncientWendigo, 8437 },
        { EnemyType.GryphonRider, 8750 },
        { EnemyType.OgreMagi, 1 }, // TODO
        { EnemyType.Abomination, 10500 },
        { EnemyType.ChaosWarden, 1 }, // TODO
        { EnemyType.MountainGiant, 15000 },
        { EnemyType.GoblinShredder, 24000 },
        { EnemyType.KodoRider, 1 }, // TODO
        { EnemyType.FrostWyrm, 36000 },
        { EnemyType.Phoenix, 135000 },
    };

    public static readonly Dictionary<EnemyType, int> GoldCost = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 5 },
        { EnemyType.Wolf, 10 },
        { EnemyType.Skeleton, 20 },
        { EnemyType.Acolyte, 35 },
        { EnemyType.Spider, 50 },
        { EnemyType.Swordsman, 70 },
        { EnemyType.Grunt, 100 },
        { EnemyType.Temptress, 150 },
        { EnemyType.Shade, 200 },
        { EnemyType.MudGolem, 350 },
        { EnemyType.Treant, 750 },
        { EnemyType.RotGolem, 1000 },
        { EnemyType.Knight, 1000 },
        { EnemyType.VengefulSpirit, 2250 },
        { EnemyType.ForestTroll, 4000 },
        { EnemyType.Wyvern, 7500 },
        { EnemyType.Voidwalker, 10000 },
        { EnemyType.FacelessOne, 12500 },
        { EnemyType.Dragonspawn, 15000 },
        { EnemyType.SeaTurtle, 20000 },
        { EnemyType.Banshee, 30000 },
        { EnemyType.SiegeEngine, 50000 },
        { EnemyType.KoboldGeomancer, 75000 },
        { EnemyType.Infernal, 100000 },
        { EnemyType.DeathRevenant, 100000 },
        { EnemyType.SatyrShadowdancer, 125000 },
        { EnemyType.CryptFiend, 150000 },
        { EnemyType.SpiritWalker, 175000 },
        { EnemyType.Necromancer, 200000 },
        { EnemyType.AncientWendigo, 225000 },
        { EnemyType.GryphonRider, 250000 },
        { EnemyType.OgreMagi, 275000 },
        { EnemyType.Abomination, 300000 },
        { EnemyType.ChaosWarden, 333333 },
        { EnemyType.MountainGiant, 500000 },
        { EnemyType.GoblinShredder, 800000 },
        { EnemyType.KodoRider, 1000000 },
        { EnemyType.FrostWyrm, 1200000 },
        { EnemyType.Phoenix, 2250000 },
    };

    public static readonly Dictionary<EnemyType, ArmorType> ArmorModifier = new Dictionary<EnemyType, ArmorType>() {
        { EnemyType.Sheep, ArmorType.Unarmored },
        { EnemyType.Wolf, ArmorType.Unarmored },
        { EnemyType.Skeleton, ArmorType.Medium },
        { EnemyType.Acolyte, ArmorType.Light },
        { EnemyType.Spider, ArmorType.Heavy },
        { EnemyType.Swordsman, ArmorType.Medium },
        { EnemyType.Grunt, ArmorType.Heavy },
        { EnemyType.Temptress, ArmorType.Light },
        { EnemyType.Shade, ArmorType.Unarmored },
        { EnemyType.MudGolem, ArmorType.Fortified },
        { EnemyType.Treant, ArmorType.Fortified },
        { EnemyType.RotGolem, ArmorType.Hero },
        { EnemyType.Knight, ArmorType.Medium },
        { EnemyType.VengefulSpirit, ArmorType.Unarmored },
        { EnemyType.ForestTroll, ArmorType.Light },
        { EnemyType.Wyvern, ArmorType.Unarmored },
        { EnemyType.Voidwalker, ArmorType.Heavy },
        { EnemyType.FacelessOne, ArmorType.Heavy },
        { EnemyType.Dragonspawn, ArmorType.Medium },
        { EnemyType.SeaTurtle, ArmorType.Fortified },
        { EnemyType.Banshee, ArmorType.Unarmored },
        { EnemyType.SiegeEngine, ArmorType.Fortified },
        { EnemyType.KoboldGeomancer, ArmorType.Light },
        { EnemyType.Infernal, ArmorType.Hero },
        { EnemyType.DeathRevenant, ArmorType.Heavy },
        { EnemyType.SatyrShadowdancer, ArmorType.Light },
        { EnemyType.CryptFiend, ArmorType.Unarmored },
        { EnemyType.SpiritWalker, ArmorType.Medium },
        { EnemyType.Necromancer, ArmorType.Unarmored },
        { EnemyType.AncientWendigo, ArmorType.Fortified },
        { EnemyType.GryphonRider, ArmorType.Light },
        { EnemyType.OgreMagi, ArmorType.Unarmored },
        { EnemyType.Abomination, ArmorType.Heavy },
        { EnemyType.ChaosWarden, ArmorType.Light },
        { EnemyType.MountainGiant, ArmorType.Fortified },
        { EnemyType.GoblinShredder, ArmorType.Medium },
        { EnemyType.KodoRider, ArmorType.Heavy },
        { EnemyType.FrostWyrm, ArmorType.Heavy },
        { EnemyType.Phoenix, ArmorType.Hero },
    };

    public static readonly Dictionary<EnemyType, int> ArmorAmount = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 0 },
        { EnemyType.Wolf, 0 },
        { EnemyType.Skeleton, 0 },
        { EnemyType.Acolyte, 0 },
        { EnemyType.Spider, 1 },
        { EnemyType.Swordsman, 1 },
        { EnemyType.Grunt, 2 },
        { EnemyType.Temptress, 2 },
        { EnemyType.Shade, 0 },
        { EnemyType.MudGolem, 2 },
        { EnemyType.Treant, 2 },
        { EnemyType.RotGolem, 5 },
        { EnemyType.Knight, 2 },
        { EnemyType.VengefulSpirit, 2 },
        { EnemyType.ForestTroll, 2 },
        { EnemyType.Wyvern, 2 },
        { EnemyType.Voidwalker, 3 },
        { EnemyType.FacelessOne, 3 },
        { EnemyType.Dragonspawn, 3 },
        { EnemyType.SeaTurtle, 4 },
        { EnemyType.Banshee, 4 },
        { EnemyType.SiegeEngine, 4 },
        { EnemyType.KoboldGeomancer, 4 },
        { EnemyType.Infernal, 12 },
        { EnemyType.DeathRevenant, 6 },
        { EnemyType.SatyrShadowdancer, 6 },
        { EnemyType.CryptFiend, 7 },
        { EnemyType.SpiritWalker, 7 },
        { EnemyType.Necromancer, 8 },
        { EnemyType.AncientWendigo, 0 },
        { EnemyType.GryphonRider, 6 },
        { EnemyType.OgreMagi, 0 }, // TODO
        { EnemyType.Abomination, 10 },
        { EnemyType.ChaosWarden, 0 }, // TODO
        { EnemyType.MountainGiant, 10 },
        { EnemyType.GoblinShredder, 12 },
        { EnemyType.KodoRider, 0 }, // TODO
        { EnemyType.FrostWyrm, 16 },
        { EnemyType.Phoenix, 20 },
    };

    public static readonly Dictionary<EnemyType, int> SpellResistanceAmount = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 0 },
        { EnemyType.Wolf, 0 },
        { EnemyType.Skeleton, 0 },
        { EnemyType.Acolyte, 0 },
        { EnemyType.Spider, 0 },
        { EnemyType.Swordsman, 0 },
        { EnemyType.Grunt, 0 },
        { EnemyType.Temptress, 0 },
        { EnemyType.Shade, 0 },
        { EnemyType.MudGolem, 0 },
        { EnemyType.Treant, 0 },
        { EnemyType.RotGolem, 0 },
        { EnemyType.Knight, 0 },
        { EnemyType.VengefulSpirit, 0 },
        { EnemyType.ForestTroll, 0 },
        { EnemyType.Wyvern, 0 },
        { EnemyType.Voidwalker, 0 },
        { EnemyType.FacelessOne, 0 },
        { EnemyType.Dragonspawn, 0 },
        { EnemyType.SeaTurtle, 0 },
        { EnemyType.Banshee, 0 },
        { EnemyType.SiegeEngine, 0 },
        { EnemyType.KoboldGeomancer, 0 },
        { EnemyType.Infernal, 0 },
        { EnemyType.DeathRevenant, 0 },
        { EnemyType.SatyrShadowdancer, 0 },
        { EnemyType.CryptFiend, 0 },
        { EnemyType.SpiritWalker, 0 },
        { EnemyType.Necromancer, 0 },
        { EnemyType.AncientWendigo, 0 },
        { EnemyType.GryphonRider, 0 },
        { EnemyType.OgreMagi, 0 },
        { EnemyType.Abomination, 0 },
        { EnemyType.ChaosWarden, 0 },
        { EnemyType.MountainGiant, 0 },
        { EnemyType.GoblinShredder, 0 },
        { EnemyType.KodoRider, 0 },
        { EnemyType.FrostWyrm, 0 },
        { EnemyType.Phoenix, 0 },
    };

    // These are all -25 from lolreported's numbers for testing purposes
    public static readonly double UniversalInitialStockDelay = 25;
    public static readonly Dictionary<EnemyType, double> InitialStockDelay = new Dictionary<EnemyType, double>() {
        { EnemyType.Sheep, 0 },
        { EnemyType.Wolf, 20 },
        { EnemyType.Skeleton, 40 },
        { EnemyType.Acolyte, 60 },
        { EnemyType.Spider, 80 },
        { EnemyType.Swordsman, 100 },
        { EnemyType.Grunt, 120 },
        { EnemyType.Temptress, 140 },
        { EnemyType.Shade, 170 },
        { EnemyType.MudGolem, 200 },
        { EnemyType.Treant, 230 },
        { EnemyType.RotGolem, 260 },
        { EnemyType.Knight, 320 },
        { EnemyType.VengefulSpirit, 350 },
        { EnemyType.ForestTroll, 380 },
        { EnemyType.Wyvern, 410 },
        { EnemyType.Voidwalker, 470 },
        { EnemyType.FacelessOne, 510 },
        { EnemyType.Dragonspawn, 550 },
        { EnemyType.SeaTurtle, 590 },
        { EnemyType.Banshee, 650 },
        { EnemyType.SiegeEngine, 700 },
        { EnemyType.KoboldGeomancer, 750 },
        { EnemyType.Infernal, 800 },
        { EnemyType.DeathRevenant, 860 },
        { EnemyType.SatyrShadowdancer, 890 },
        { EnemyType.CryptFiend, 920 },
        { EnemyType.SpiritWalker, 950 },
        { EnemyType.Necromancer, 1010 },
        { EnemyType.AncientWendigo, 1050 },
        { EnemyType.GryphonRider, 1090 },
        { EnemyType.OgreMagi, 1130 },
        { EnemyType.Abomination, 1190 },
        { EnemyType.ChaosWarden, 1220 },
        { EnemyType.MountainGiant, 1250 },
        { EnemyType.GoblinShredder, 1250 },
        { EnemyType.KodoRider, 1310 },
        { EnemyType.FrostWyrm, 1400 },
        { EnemyType.Phoenix, 1550 },
    };

    // All but sheep/wolf are 1
    public static readonly Dictionary<EnemyType, int> InitialStockAmountAfterDelay =
        new Dictionary<EnemyType, int>() {
            { EnemyType.Sheep, 3 },
            { EnemyType.Wolf, 3 },
            { EnemyType.Skeleton, 1 },
            { EnemyType.Acolyte, 1 },
            { EnemyType.Spider, 1 },
            { EnemyType.Swordsman, 1 },
            { EnemyType.Grunt, 1 },
            { EnemyType.Temptress, 1 },
            { EnemyType.Shade, 1 },
            { EnemyType.MudGolem, 1 },
            { EnemyType.Treant, 1 },
            { EnemyType.RotGolem, 1 },
            { EnemyType.Knight, 1 },
            { EnemyType.VengefulSpirit, 1 },
            { EnemyType.ForestTroll, 1 },
            { EnemyType.Wyvern, 1 },
            { EnemyType.Voidwalker, 1 },
            { EnemyType.FacelessOne, 1 },
            { EnemyType.Dragonspawn, 1 },
            { EnemyType.SeaTurtle, 1 },
            { EnemyType.Banshee, 1 },
            { EnemyType.SiegeEngine, 1 },
            { EnemyType.KoboldGeomancer, 1 },
            { EnemyType.Infernal, 1 },
            { EnemyType.DeathRevenant, 1 },
            { EnemyType.SatyrShadowdancer, 1 },
            { EnemyType.CryptFiend, 1 },
            { EnemyType.SpiritWalker, 1 },
            { EnemyType.Necromancer, 1 },
            { EnemyType.AncientWendigo, 1 },
            { EnemyType.GryphonRider, 1 },
            { EnemyType.OgreMagi, 1 },
            { EnemyType.Abomination, 1 },
            { EnemyType.ChaosWarden, 1 },
            { EnemyType.MountainGiant, 1 },
            { EnemyType.GoblinShredder, 1 },
            { EnemyType.KodoRider, 1 },
            { EnemyType.FrostWyrm, 1 },
            { EnemyType.Phoenix, 1 },
        };

    public static readonly Dictionary<EnemyType, double> StockIncrementTimer = new Dictionary<EnemyType, double>() {
        { EnemyType.Sheep, TraitConstants.FastProducingRestockInterval }, // TODO: Maybe turn this into a trait behaviour thing and not a constant
        { EnemyType.Wolf, TraitConstants.FastProducingRestockInterval },
        { EnemyType.Skeleton, 5 },
        { EnemyType.Acolyte, 5 },
        { EnemyType.Spider, 5 },
        { EnemyType.Swordsman, 5 },
        { EnemyType.Grunt, 5 },
        { EnemyType.Temptress, 5 },
        { EnemyType.Shade, 5 },
        { EnemyType.MudGolem, 5 },
        { EnemyType.Treant, 5 },
        { EnemyType.RotGolem, 10 },
        { EnemyType.Knight, 5 },
        { EnemyType.VengefulSpirit, 5 },
        { EnemyType.ForestTroll, 5 },
        { EnemyType.Wyvern, 5 },
        { EnemyType.Voidwalker, 5 },
        { EnemyType.FacelessOne, 5 },
        { EnemyType.Dragonspawn, 5 },
        { EnemyType.SeaTurtle, 5 },
        { EnemyType.Banshee, 5 },
        { EnemyType.SiegeEngine, 5 },
        { EnemyType.KoboldGeomancer, 5 },
        { EnemyType.Infernal, 10 },
        { EnemyType.DeathRevenant, 5 },
        { EnemyType.SatyrShadowdancer, 5 },
        { EnemyType.CryptFiend, 5 },
        { EnemyType.SpiritWalker, 5 },
        { EnemyType.Necromancer, 5 },
        { EnemyType.AncientWendigo, 5 },
        { EnemyType.GryphonRider, 5 },
        { EnemyType.OgreMagi, 5 },
        { EnemyType.Abomination, 5 },
        { EnemyType.ChaosWarden, 5 },
        { EnemyType.MountainGiant, 5 },
        { EnemyType.GoblinShredder, 5 },
        { EnemyType.KodoRider, 5 },
        { EnemyType.FrostWyrm, 5 },
        { EnemyType.Phoenix, 15 },
    };

    public static readonly Dictionary<EnemyType, int> MaxStock = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 32 },
        { EnemyType.Wolf, 32 },
        { EnemyType.Skeleton, 32 },
        { EnemyType.Acolyte, 32 },
        { EnemyType.Spider, 32 },
        { EnemyType.Swordsman, 32 },
        { EnemyType.Grunt, 32 },
        { EnemyType.Temptress, 32 },
        { EnemyType.Shade, 16 },
        { EnemyType.MudGolem, 32 },
        { EnemyType.Treant, 16 },
        { EnemyType.RotGolem, 8 },
        { EnemyType.Knight, 32 },
        { EnemyType.VengefulSpirit, 32 },
        { EnemyType.ForestTroll, 32 },
        { EnemyType.Wyvern, 16 },
        { EnemyType.Voidwalker, 32 },
        { EnemyType.FacelessOne, 32 },
        { EnemyType.Dragonspawn, 32 },
        { EnemyType.SeaTurtle, 32 },
        { EnemyType.Banshee, 16 },
        { EnemyType.SiegeEngine, 16 },
        { EnemyType.KoboldGeomancer, 32 },
        { EnemyType.Infernal, 8 },
        { EnemyType.DeathRevenant, 32 },
        { EnemyType.SatyrShadowdancer, 32 },
        { EnemyType.CryptFiend, 32 },
        { EnemyType.SpiritWalker, 32 },
        { EnemyType.Necromancer, 32 },
        { EnemyType.AncientWendigo, 32 },
        { EnemyType.GryphonRider, 16 },
        { EnemyType.OgreMagi, 32 },
        { EnemyType.Abomination, 32 },
        { EnemyType.ChaosWarden, 32 },
        { EnemyType.MountainGiant, 16 },
        { EnemyType.GoblinShredder, 32 },
        { EnemyType.KodoRider, 32 },
        { EnemyType.FrostWyrm, 16 },
        { EnemyType.Phoenix, 4 },
    };

    public static readonly Dictionary<EnemyType, int> NumberOfUnitsPerSend = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 3 },
        { EnemyType.Wolf, 3 },
        { EnemyType.Skeleton, 3 },
        { EnemyType.Acolyte, 3 },
        { EnemyType.Spider, 3 },
        { EnemyType.Swordsman, 3 },
        { EnemyType.Grunt, 3 },
        { EnemyType.Temptress, 3 },
        { EnemyType.Shade, 3 },
        { EnemyType.MudGolem, 3 },
        { EnemyType.Treant, 3 },
        { EnemyType.RotGolem, 1 },
        { EnemyType.Knight, 3 },
        { EnemyType.VengefulSpirit, 3 },
        { EnemyType.ForestTroll, 3 },
        { EnemyType.Wyvern, 3 },
        { EnemyType.Voidwalker, 3 },
        { EnemyType.FacelessOne, 3 },
        { EnemyType.Dragonspawn, 3 },
        { EnemyType.SeaTurtle, 3 },
        { EnemyType.Banshee, 3 },
        { EnemyType.SiegeEngine, 3 },
        { EnemyType.KoboldGeomancer, 3 },
        { EnemyType.Infernal, 1 },
        { EnemyType.DeathRevenant, 3 },
        { EnemyType.SatyrShadowdancer, 3 },
        { EnemyType.CryptFiend, 3 },
        { EnemyType.SpiritWalker, 3 },
        { EnemyType.Necromancer, 3 },
        { EnemyType.AncientWendigo, 3 },
        { EnemyType.GryphonRider, 3 },
        { EnemyType.OgreMagi, 3 },
        { EnemyType.Abomination, 3 },
        { EnemyType.ChaosWarden, 3 },
        { EnemyType.MountainGiant, 3 },
        { EnemyType.GoblinShredder, 3 },
        { EnemyType.KodoRider, 3 },
        { EnemyType.FrostWyrm, 3 },
        { EnemyType.Phoenix, 1 },
    };

    public static readonly Dictionary<EnemyType, int> NumberOfLivesToSteal = new Dictionary<EnemyType, int>() {
        { EnemyType.Sheep, 1 },
        { EnemyType.Wolf, 1 },
        { EnemyType.Skeleton, 1 },
        { EnemyType.Acolyte, 1 },
        { EnemyType.Spider, 1 },
        { EnemyType.Swordsman, 1 },
        { EnemyType.Grunt, 1 },
        { EnemyType.Temptress, 1 },
        { EnemyType.Shade, 1 },
        { EnemyType.MudGolem, 1 },
        { EnemyType.Treant, 1 },
        { EnemyType.RotGolem, 2 },
        { EnemyType.Knight, 1 },
        { EnemyType.VengefulSpirit, 1 },
        { EnemyType.ForestTroll, 1 },
        { EnemyType.Wyvern, 1 },
        { EnemyType.Voidwalker, 1 },
        { EnemyType.FacelessOne, 1 },
        { EnemyType.Dragonspawn, 1 },
        { EnemyType.SeaTurtle, 1 },
        { EnemyType.Banshee, 1 },
        { EnemyType.SiegeEngine, 1 },
        { EnemyType.KoboldGeomancer, 1 },
        { EnemyType.Infernal, 2 },
        { EnemyType.DeathRevenant, 1 },
        { EnemyType.SatyrShadowdancer, 1 },
        { EnemyType.CryptFiend, 1 },
        { EnemyType.SpiritWalker, 1 },
        { EnemyType.Necromancer, 1 },
        { EnemyType.AncientWendigo, 1 },
        { EnemyType.GryphonRider, 1 },
        { EnemyType.OgreMagi, 1 },
        { EnemyType.Abomination, 1 },
        { EnemyType.ChaosWarden, 1 },
        { EnemyType.MountainGiant, 1 },
        { EnemyType.GoblinShredder, 1 },
        { EnemyType.KodoRider, 1 },
        { EnemyType.FrostWyrm, 1 },
        { EnemyType.Phoenix, 2 },
    };

    public static readonly HashSet<EnemyType> FullyImplementedCreeps = new HashSet<EnemyType>() {
        EnemyType.Sheep,
        EnemyType.Wolf,
        EnemyType.Skeleton,
        EnemyType.Acolyte,
        EnemyType.Spider,
        EnemyType.Swordsman,
        EnemyType.Grunt,
        EnemyType.Temptress,
        EnemyType.Shade,
        EnemyType.MudGolem,
        EnemyType.Treant,
        EnemyType.RotGolem,
        EnemyType.Knight,
        EnemyType.VengefulSpirit,
        EnemyType.ForestTroll,
        EnemyType.Wyvern,
        EnemyType.Voidwalker,
        EnemyType.FacelessOne,
        EnemyType.Dragonspawn,
        EnemyType.SeaTurtle,
        EnemyType.Banshee,
        EnemyType.SiegeEngine,
        EnemyType.KoboldGeomancer,
        EnemyType.Infernal,
        EnemyType.DeathRevenant,
        EnemyType.SatyrShadowdancer,
        EnemyType.CryptFiend,
        EnemyType.SpiritWalker,
        EnemyType.Necromancer,
        EnemyType.AncientWendigo,
        EnemyType.GryphonRider,
        EnemyType.OgreMagi,
        EnemyType.Abomination,
        EnemyType.ChaosWarden,
        EnemyType.MountainGiant,
        EnemyType.GoblinShredder,
        EnemyType.KodoRider,
        EnemyType.FrostWyrm,
        EnemyType.Phoenix,
    };
}
